### ISSUE TITLE
docs: Continuous deployment

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next-docs#12]
I tried to set a Github Action to automatically build and deploy docs, but I lack the ability to set up Secrets in this repo. I guess we should wait until both repos are merged and then work from there?

Also it would be cool to leverage Netlify, just as docs-next is doing.

I'll keep updating manually for now 👍

**Comment by dobromir-hristov** [comment]
Why not just use Netlify?

**Comment by afontcu** [comment]
yeah! that was my first option. I think we should just wait until both repos are merged, and then set up the CD for docs there?

**Comment by afontcu** [comment]
Closing this up as we're currently deploying on master merge :) We'll look into that again when repos are merged
