### ISSUE TITLE
UI/UX: Better landing page

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next-docs#18]
https://vuejs.github.io/vue-test-utils-next-docs/

It's not very good. Let's put something here?

- example component/test?
- example output?
- list some features?

Alternatively we remove this page and redirect here: https://vuejs.github.io/vue-test-utils-next-docs/guide/introduction.html

What do you all think?

**Comment by dobromir-hristov** [comment]
Those pages are generally full of pointless text, that no one reads really 😆 

Either design it pretty (which no one has time afaik) or just redirect to the important parts and, which is Intro

**Comment by lmiller1990** [comment]
I would be happy to just redirect.

**Comment by afontcu** [comment]
+1 to simply redirect to Introduction until we come up with better content for the homepage

**Comment by afontcu** [comment]
Looks like redirecting the homepage in Vuepress is not as straightforward as one might think 😅… I'd leave this as-is for now, and the minute we merge this repo with VTU and set up Netlify, we can redirect from there.

**Comment by lmiller1990** [comment]
Yes, I tried this too... hard.

Looks like Netlify/DNS level redirect is best.

Regarding merging this with the main projects we have two options:

1. move to Vitepress (no more Vue conflict, we get to use Vitepress!)
2. mono repo (I can set this up in about 20m) then we can keep Vue 2 and Vue 3 deps separate

I really doubt Vuepress is moving to Vue 3 any time soon, so that probably isn't an option.

Which one do you prefer?

I do like the idea of having docs and source in one place.

**Comment by afontcu** [comment]
TBH… I'm a bit scared of monorepos 😂 from what I've seen, they tend to grow into something that's hard to grasp for contributors and hard to maintain. This is totally biased, of course.

That being said, using Vitepress is kind of _exciting_? So I'd go with 1. Not sure about feature parity, but right now we're using a really small set of them from Vuepress:

- Syntax highlighting (with line highlighting, that's really cool).
- Alert banners.
- Search input.

**Comment by lmiller1990** [comment]
I also dislike monorepos generally, definitely in this case. In the case of vue-next it makes sense - here it certainly doesn't. Glad we are on the same page :)

I am crazy busy atm, but if I have some time I will try out Vitepress and see if it meets those minimum criteria. If not... good chance to to contribute to the Vite ecosystem 🎉

**Comment by afontcu** [comment]
Closing for now! We merged repos and landing page now looks like vue router's and vuex', so we're good! Any improvement will be appreciated, though 😄
