### ISSUE TITLE
Suggested way for docs to show mocking axios?

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next-docs#25]
Hi! 👋  I was writing docs for Making HTTP Requests, and I had this doubt.

There are several ways of mocking a module in Jest, and I'm not sure which one is the one we should showcase in docs:

```js
jest.mock('axios')
axios.get = jest.fn().mockResolvedValue(posts)
```

```js
jest.mock('axios', () => ({
  get: jest.fn(() => posts)
}))
```

```js
jest.mock('axios')
axios.get.mockResolvedValue(fakePostList)
```

any preference? any downsides?

disclaimer: docs will mention alternatives such as [`axios-mock-adapter`](https://github.com/ctimmerm/axios-mock-adapter) or [`msw`](https://github.com/mswjs/msw), but I want to keep it simple for the example.

**Comment by lmiller1990** [comment]
I always use the second one. Not sure if this is good practice or not but I often have components making multiple API calls, and I test them like this:

```ts
import { mockPosts } from './posts'
import { mockUsers } from './users'

jest.mock('axios', () => ({
  get: (url) => {  
    if (url === '/posts') {
      return { data: mockPosts }
    }

    if (url === '/users') {
      return { data: mockUsers }
    }
  }
}))
```

I guess `mockResolvedValue` is probably the "correct" way to do this, it feels more "jest-y", but I don't know how you handle multiple urls in that case 🤔

**Comment by afontcu** [comment]
I ended up using the second one in #26 :)
