### ISSUE TITLE
feat: Add Stubs/Shallow Mount section

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next-docs#29]
https://github.com/vuejs/vue-test-utils-next-docs/blob/master/src/guide/stubs-shallow-mount.md

**Comment by lmiller1990** [comment]
I think @dobromir-hristov was interested in writing this one.

@NataliaTepluhina also has a lot of knowledge on how/when to use these from her experience working on a huge Vue codebase at GitLab. We should definitely ask if she can review this section.

**Comment by dobromir-hristov** [comment]
Yep, give me a day or two :)

**Comment by lmiller1990** [comment]
No rush 🖖

**Comment by lmiller1990** [comment]
I will work on this one, I have some ideas.

Main points:

- stubs
- shallow: true
- the slot stuff
- "old" vs "new" behavior

**Comment by afontcu** [comment]
cool! Are you planning to add some pro's and con's of using stubs and shallow mount? Similar to what Cypress does on [Testing Strategies for Network Requests](https://docs.cypress.io/guides/guides/network-requests.html#Testing-Strategies).

disclaimer: it might not be the place, and that content might live somewhere else! 😇

**Comment by lmiller1990** [comment]
Yes, I think we should include pros and cons. This section should be mostly un-opinionated, though. I'll get a few reviews from different people on this one, especially @dobromir-hristov  and @NataliaTepluhina who have a lot more experience than me with `stubs` and `shallowMount` in very large applications.
