### ISSUE TITLE
Add asserting hidden elements to Conditional Rendering

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next-docs#47]
We're missing a section for the resurrected `isVisible()`, showing how to test hidden content (using `v-show`, for instance).

**Comment by lmiller1990** [comment]
After various discussion I think we should bring back `isVisible`. Steal it from the jest-dom matchers.

**Comment by afontcu** [comment]
Yeah, followed the discussion. Not 100% sold, but I agree having v-if/v-show parity makes sense 👍  I'll rephrase the OP.

**Comment by lmiller1990** [comment]
I agree on using the test runner where we can, but nothing having a built in way to test `v-show` is not ideal.

Another thing I have learned maintaining OSS is sometimes you need to make compromises.  🤷‍♂️  I don't think this is so bad, it doesn't really promote any bad practices like some of the other deprecations. 👍

**Comment by afontcu** [comment]
> it doesn't really promote any bad practices like some of the other deprecations. 👍

Yeah, that's a good consideration!

**Comment by lmiller1990** [comment]
`isVisible` is back in v1 due to popular demand.

We need it in v2.

**Comment by lmiller1990** [comment]
`isVisible` is back now. We should write this.

**Comment by AngeloGulina** [comment]
Hi @afontcu – given this is assigned to you I was wondering if you're already working on this part or I can try push an proposal PR we can discuss on? Thanks!

**Comment by afontcu** [comment]
Hi @AngeloGulina! Had some ideas an a really early draft, but nothing set in stone :) more than happy to check your proposal! ❤️  I'll go ahead and assign the issue to you.

Cheers!

**Comment by AngeloGulina** [comment]
@afontcu we can now close this one I guess!
