### ISSUE TITLE
Document global.config

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next-docs#49]
We support config but we did not document it

It's here https://github.com/vuejs/vue-test-utils-next/blob/e5aee88ec6437a7d28dd0a4a9d0e84bbe3a8df40/src/types.ts#L24

**Comment by afontcu** [comment]
Do you believe this is enough? https://vue-test-utils.vuejs.org/v2/api/#global-config

**Comment by lmiller1990** [comment]
Yes!
