### ISSUE TITLE
Update docs on plugins to show you can pass options

### ISSUE THREAD

**Issue by lmiller1990** [vuejs/vue-test-utils-next-docs#64]
ref: https://github.com/vuejs/vue-test-utils-next/issues/255

**Comment by mohit-vora** [comment]
@lmiller1990 I came here from https://goodfirstissues.com/ and trying to contribute here for the first time ever. :) I choose this repo because I worked with VueJS to create a simple website and I love Vue.

Please help me out here. How do I assign this issue to myself and open a pull request? I don't see any options on this page to do that.

**Comment by lmiller1990** [comment]
Hi @mohit-vora! Welcome to open source.

1. First you will want to clone the repository. Click here:

![image](https://user-images.githubusercontent.com/19196536/99923554-faff5280-2d81-11eb-96e7-375d3b0254ab.png)

2. It will be forked and you have a repository under your own name. Get the URL and run `git clone <url>` to clone it. 

![image](https://user-images.githubusercontent.com/19196536/99923582-19654e00-2d82-11eb-94f2-ce5e8a6c0dc5.png)

3. Make your changes locally. You will probably edit the API.md file. You can preview how it will look by running `yarn install` to install the deps and `yarn serve` to start the server locally.

4. Add your changes. `git add .` 

5. Commit `git commit -m "docs: update plugins docs"

6. `git push`

7. Come to THIS repo (not your cloned one) and click "Pull Requests" and click "New Pull Request"

![image](https://user-images.githubusercontent.com/19196536/99923673-87aa1080-2d82-11eb-8a56-addd32797b01.png)

8. Choose your fork as the one to make the pull request from.

9. Write a useful description and assign someone to review it.

Hopefully that helps.

**Comment by mohit-vora** [comment]
@lmiller1990 Thank you for detailed steps. Really helped get started fast. I reached till step 6, all well.
On step 7, when I try to create a pull request, I do not see my fork in the list. Also, I did not create a new branch of my own in my fork, directly pushed on master in my fork. Should I have created a branch in my fork first and then create a pull request in original parent project for it to show up in Pull Request page?

**Comment by lmiller1990** [comment]
Try clicking "Pull Request" on your own fork of the repo - that might work. No need to change branch - you should be able to make a PR from your fork's master branch.

You can put "resolves #64" in the PR description. When it is merged, it will close this issue automatically. Or we can just close this manually when it is merged.
