### ISSUE TITLE
feat: add Vue Router section

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next-docs#7]
* showcase how to mock Vue Router.
* showcase how to use `router-link-stub` ([source](https://github.com/vuejs/vue-test-utils-next/pull/49#issuecomment-610894821)).
* avoid common pitfalls when trying to assert against a URL.

**Comment by lmiller1990** [comment]
I would like to work on this one. I learned a lot about the new Vue Router and the pitfalls (see [here](https://github.com/vuejs/vue-router-next/issues/330#issuecomment-650661328) for example).

**Comment by afontcu** [comment]
Sounds great!

**Comment by posva** [comment]
Ping me for a review when you have something. I already had some ideas about things to add so I could help on this one

**Comment by lmiller1990** [comment]
@posva will do, would be great to get your review. Anything you think is especially important to mention?

**Comment by posva** [comment]
Nothing specific but it would be useful being able to change the current location easily

**Comment by lmiller1990** [comment]
I will hold off on this one until we discuss router testing more here: https://github.com/vuejs/vue-test-utils-next/issues/152

**Comment by afontcu** [comment]
Closed in #43

**Comment by lmiller1990** [comment]
We might want to consider adding something about Vue Mock Router: https://github.com/posva/vue-router-mock

**Comment by afontcu** [comment]
Right! Let me create a new issue
