### ISSUE TITLE
feat: add "How to test passing props" section

### ISSUE THREAD

**Issue by afontcu** [vuejs/vue-test-utils-next-docs#9]
One of the common frictions in VTU is how to test that given a prop, something happens in the component under testing.

We should explain:

* How to pass in props, and assert the expected behavior _(a special case is a prop that triggers some sort of behaviour in `created` or `mounted`)_.
* How to "update" that prop. This might change depending on the final VTU API ([related](https://github.com/vuejs/rfcs/pull/151#discussion_r399801145)), but we could "officialy" suggest using a Wrapper component for the time being.

**Comment by dobromir-hristov** [comment]
@afontcu exactly how I imagine it as well. `setProps` is not added, so it is a viable option for point 3.
People can also pass a `ref` to test watchers, which is basically what `setProps` kind of does.

Do you need help with this?

**Comment by afontcu** [comment]
> Do you need help with this?

by all means! :) I think this would make great content for the "Passing Data" guide section (https://github.com/vuejs/vue-test-utils-next-docs/blob/master/src/guide/passing-data.md).

It would be great if the whole section used the same evolving component, so people can easily jump from snippet to snippet.

**Comment by lmiller1990** [comment]
I can add it to passing data.

**Comment by dobromir-hristov** [comment]
OK then its up to you bud.

**Comment by lmiller1990** [comment]
Thinking of an example that illustrates all three of those use cases is very difficult. I had the idea to use a `<Password>` component that takes a `minLength` and `maxLength` prop where use use the `props` mounting option change the values and assert the correct error is rendered.

This does lend itself well to an example of changing props - those validations would never change.

Any ideas?

Alternatively we can consider different examples for each case.

**Comment by dobromir-hristov** [comment]
I think we are fine with 3 simple components examples. No need to overthink it?

**Comment by afontcu** [comment]
Sure! Would've been great to find a valid example for the 3 scenarios (thought about it a bit), but couldn't come up with a solid use case. So I'd just go ahead and keep the three components as simple as possible so there isn't much cognitive overload in a single guide.

**Comment by dobromir-hristov** [comment]
Is there something already on this that we can checkout?

**Comment by lmiller1990** [comment]
Not yet, I started something but it's very half baked. Are you interested in picking this up @dobromir-hristov ?

**Comment by dobromir-hristov** [comment]
Push to a branch, i can continue
